In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(r"D:\ipl_data\IPL Matches 2008-2020.csv")

df.head(5)

id        city        date player_of_match  \
0  335982   Bangalore  2008-04-18     BB McCullum   
1  335983  Chandigarh  2008-04-19      MEK Hussey   
2  335984       Delhi  2008-04-19     MF Maharoof   
3  335985      Mumbai  2008-04-20      MV Boucher   
4  335986     Kolkata  2008-04-20       DJ Hussey   

                                        venue  neutral_venue  \
0                       M Chinnaswamy Stadium              0   
1  Punjab Cricket Association Stadium, Mohali              0   
2                            Feroz Shah Kotla              0   
3                            Wankhede Stadium              0   
4                                Eden Gardens              0   

                         team1                        team2  \
0  Royal Challengers Bangalore        Kolkata Knight Riders   
1              Kings XI Punjab          Chennai Super Kings   
2             Delhi Daredevils             Rajasthan Royals   
3               Mumbai Indians  Royal Challengers Bangalore   
4        Kolkata Knight Riders              Deccan Chargers   

                   toss_winner toss_decision                       winner  \
0  Royal Challengers Bangalore         field        Kolkata Knight Riders   
1          Chennai Super Kings           bat          Chennai Super Kings   
2             Rajasthan Royals           bat             Delhi Daredevils   
3               Mumbai Indians           bat  Royal Challengers Bangalore   
4              Deccan Chargers           bat        Kolkata Knight Riders   

    result  result_margin eliminator method    umpire1         umpire2  
0     runs          140.0          N    NaN  Asad Rauf     RE Koertzen  
1     runs           33.0          N    NaN  MR Benson      SL Shastri  
2  wickets            9.0          N    NaN  Aleem Dar  GA Pratapkumar  
3  wickets            5.0          N    NaN   SJ Davis       DJ Harper  
4  wickets            5.0          N    NaN  BF Bowden     K Hariharan

In [3]:
df.shape

(816, 17)

In [4]:
df.keys()

Index(['id', 'city', 'date', 'player_of_match', 'venue', 'neutral_venue',
       'team1', 'team2', 'toss_winner', 'toss_decision', 'winner', 'result',
       'result_margin', 'eliminator', 'method', 'umpire1', 'umpire2'],
      dtype='object')

In [5]:
df.isnull().sum()

id                   0
city                13
date                 0
player_of_match      4
venue                0
neutral_venue        0
team1                0
team2                0
toss_winner          0
toss_decision        0
winner               4
result               4
result_margin       17
eliminator           4
method             797
umpire1              0
umpire2              0
dtype: int64

In [7]:
df1 = df.drop(['method'],axis=1)
df1.isnull().sum()

id                  0
city               13
date                0
player_of_match     4
venue               0
neutral_venue       0
team1               0
team2               0
toss_winner         0
toss_decision       0
winner              4
result              4
result_margin      17
eliminator          4
umpire1             0
umpire2             0
dtype: int64

In [8]:
df2 = df1.dropna(axis=0)
df2.isnull().sum()

id                 0
city               0
date               0
player_of_match    0
venue              0
neutral_venue      0
team1              0
team2              0
toss_winner        0
toss_decision      0
winner             0
result             0
result_margin      0
eliminator         0
umpire1            0
umpire2            0
dtype: int64

In [10]:
df2['player_of_match'].value_counts()

AB de Villiers    22
CH Gayle          22
RG Sharma         18
MS Dhoni          17
DA Warner         17
                  ..
AD Mathews         1
AS Joseph          1
R McLaren          1
DJ Hooda           1
LJ Wright          1
Name: player_of_match, Length: 232, dtype: int64

In [11]:
df2['player_of_match'].value_counts()[0:10]

AB de Villiers    22
CH Gayle          22
RG Sharma         18
MS Dhoni          17
DA Warner         17
SR Watson         16
YK Pathan         15
SK Raina          14
G Gambhir         13
V Kohli           12
Name: player_of_match, dtype: int64

In [ ]:
x_axis = list(df2['player_of_match'].value_counts()[0:5].keys())
y_axis = list(df2['player_of_match'].value_counts()[0:5])

plt.bar(x_axis,y_axis)
plt.title('top 5 man of the match')
plt.xlabel('players')
plt.ylabel('count')
plt.show()

In [18]:
df.keys()

Index(['id', 'city', 'date', 'player_of_match', 'venue', 'neutral_venue',
       'team1', 'team2', 'toss_winner', 'toss_decision', 'winner', 'result',
       'result_margin', 'eliminator', 'method', 'umpire1', 'umpire2'],
      dtype='object')

In [20]:
final = df2[['team1','team2','winner','toss_winner','eliminator','toss_decision']]

In [35]:
all_teams = df2['team1'].unique()
all_teams

array(['Royal Challengers Bangalore', 'Kings XI Punjab',
       'Delhi Daredevils', 'Mumbai Indians', 'Kolkata Knight Riders',
       'Rajasthan Royals', 'Deccan Chargers', 'Chennai Super Kings',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Gujarat Lions', 'Rising Pune Supergiants',
       'Rising Pune Supergiant', 'Delhi Capitals'], dtype=object)

In [38]:
type(all_teams)

numpy.ndarray

In [39]:
all_teams.tolist()

['Royal Challengers Bangalore',
 'Kings XI Punjab',
 'Delhi Daredevils',
 'Mumbai Indians',
 'Kolkata Knight Riders',
 'Rajasthan Royals',
 'Deccan Chargers',
 'Chennai Super Kings',
 'Kochi Tuskers Kerala',
 'Pune Warriors',
 'Sunrisers Hyderabad',
 'Gujarat Lions',
 'Rising Pune Supergiants',
 'Rising Pune Supergiant',
 'Delhi Capitals']

In [41]:
from sklearn.preprocessing import LabelEncoder
teams = LabelEncoder()
teams.fit(all_teams)

encoded_teams = teams.transform(all_teams)
print(encoded_teams)

[13  5  3  8  7 10  1  0  6  9 14  4 12 11  2]


In [42]:
X = final[['team1', 'team2', 'toss_decision', 'toss_winner','eliminator']]
y = final[['winner']]

In [43]:
X = np.array(X)
y = np.array(y)

In [45]:
print(X)

[['Royal Challengers Bangalore' 'Kolkata Knight Riders' 'field'
  'Royal Challengers Bangalore' 'N']
 ['Kings XI Punjab' 'Chennai Super Kings' 'bat' 'Chennai Super Kings' 'N']
 ['Delhi Daredevils' 'Rajasthan Royals' 'bat' 'Rajasthan Royals' 'N']
 ...
 ['Royal Challengers Bangalore' 'Sunrisers Hyderabad' 'field'
  'Sunrisers Hyderabad' 'N']
 ['Delhi Capitals' 'Sunrisers Hyderabad' 'bat' 'Delhi Capitals' 'N']
 ['Delhi Capitals' 'Mumbai Indians' 'bat' 'Delhi Capitals' 'N']]


In [46]:
X[:, 0] = teams.transform(X[:, 0])
X[:, 1] = teams.transform(X[:, 1])
X[:, 3] = teams.transform(X[:, 3])

y[:, 0] = teams.transform(y[:, 0])

In [47]:
X

array([[13, 7, 'field', 13, 'N'],
       [5, 0, 'bat', 0, 'N'],
       [3, 10, 'bat', 10, 'N'],
       ...,
       [13, 14, 'field', 14, 'N'],
       [2, 14, 'bat', 2, 'N'],
       [2, 8, 'bat', 2, 'N']], dtype=object)

In [48]:
fb = {'field' : 0, 'bat' : 1}
for i in range(len(X)):
    X[i][2] = fb[X[i][2]]

In [49]:
X

array([[13, 7, 0, 13, 'N'],
       [5, 0, 1, 0, 'N'],
       [3, 10, 1, 10, 'N'],
       ...,
       [13, 14, 0, 14, 'N'],
       [2, 14, 1, 2, 'N'],
       [2, 8, 1, 2, 'N']], dtype=object)

In [50]:
eli = {'N': 0,'Y' : 1}
for i in range(len(X)):
    X[i][4] = eli[X[i][4]]

In [51]:
X

array([[13, 7, 0, 13, 0],
       [5, 0, 1, 0, 0],
       [3, 10, 1, 10, 0],
       ...,
       [13, 14, 0, 14, 0],
       [2, 14, 1, 2, 0],
       [2, 8, 1, 2, 0]], dtype=object)

In [53]:
X = np.array(X,dtype='int32')
y = np.array(y,dtype='int32')

In [55]:
ones, zeros = 0,0
for i in range(len(X)):
    if y[i] == X[i][0] :
        if zeros <= 375:
            y[i] = 0
            zeros += 1
        else:
            y[i] = 1
            ones += 1
            t = X[i][0]
            X[i][0] = X[i][1] 
            X[i][1] = t
        
    
        
    if y[i] == X[i][1] :
        if ones <= 375:
            y[i] = 1
            ones += 1
        else:
            y[i] = 0
            zeros += 1
            t = X[i][0]
            X[i][0] = X[i][1] 
            X[i][1] = t

In [58]:
print(np.unique(y, return_counts=True))

(array([0, 1]), array([374, 412], dtype=int64))


In [59]:
from sklearn.model_selection import train_test_split

In [60]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.05)

In [61]:
from sklearn import linear_model
lm = linear_model.LinearRegression()
lm.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [63]:
lm.score(X_test,y_test)

0.07038493488423947

In [64]:
from sklearn.svm import SVC
sv = SVC().fit(X_train, y_train)

C:\Users\nikhi\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [65]:
sv.score(X_test,y_test)

0.5

In [66]:
from sklearn.linear_model import SGDClassifier
sg = SGDClassifier(loss="hinge", penalty="l2", max_iter=5)
sg.fit(X_train,y_train)

C:\Users\nikhi\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\nikhi\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)


SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge', max_iter=5,
              n_iter_no_change=5, n_jobs=None, penalty='l2', power_t=0.5,
              random_state=None, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [67]:
sg.score(X_test,y_test)

0.425

In [68]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier().fit(X_train, y_train)

In [69]:
dt.score(X_test,y_test)

0.5

In [70]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=250).fit(X, y)

C:\Users\nikhi\anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


In [73]:
rf.score(X_test,y_test)

0.85

In [80]:
test = np.array([4,2, 1, 4,0]).reshape(1,-1)
lm.predict(test)

array([[0.5288712]])

In [81]:
sv.predict(test)

array([1])

In [82]:
sg.predict(test)


array([0])

In [83]:
dt.predict(test)


array([1])

In [84]:
rf.predict(test)

array([1])

In [87]:
import pickle as pkl

with open('ipl.pkl', 'wb') as f:
    pkl.dump(rf, f)